//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sivel_proyecto_bad115.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BODEGAS
    {
        public BODEGAS()
        {
            this.UBICACIONES = new HashSet<UBICACIONES>();
        }
    
        public int ID_BODEGA { get; set; }
        public string NOMBRE { get; set; }
        public int CAPACIDAD_MAX { get; set; }
    
        public virtual ICollection<UBICACIONES> UBICACIONES { get; set; }
    }
}
