//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sivel_proyecto_bad115.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BODEGAS
    {
        public BODEGAS()
        {
            this.UBICACIONES = new HashSet<UBICACIONES>();
        }
    
        public int ID_BODEGA { get; set; }
        [Required]
        [MaxLength(50)]
        [Display(Name = "Nombre")]
        public string NOMBRE { get; set; }
        [Required]
        [Display(Name = "Capacidad maxima")]
        public int CAPACIDAD_MAX { get; set; }
    
        public virtual ICollection<UBICACIONES> UBICACIONES { get; set; }
    }
}
