//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sivel_proyecto_bad115.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORTADORES
    {
        public IMPORTADORES()
        {
            this.IMPORTACIONES = new HashSet<IMPORTACIONES>();
        }
    
        public int ID_IMPORTADOR { get; set; }
        public int NIT { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string APELLIDO_CASADA { get; set; }
        public string GENERO { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public string DIRECCION { get; set; }
        public string PERSONA_RESPONSABLE { get; set; }
        public string TELEFONO_RESPONSABLE { get; set; }
        public string EMAIL { get; set; }
    
        public virtual ICollection<IMPORTACIONES> IMPORTACIONES { get; set; }
    }
}
