//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sivel_proyecto_bad115.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLES
    {
        public ROLES()
        {
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public int ID_ROL { get; set; }
        public string ROL { get; set; }
    
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}
