//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sivel_proyecto_bad115.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TIPO_REMOLQUES
    {
        public TIPO_REMOLQUES()
        {
            this.MOVIMIENTOS = new HashSet<MOVIMIENTOS>();
        }
    
        public int ID_TREMOLQUE { get; set; }
        [Required]
        [Display(Name = "Tipo remolque")]
        public string TIPO_REMOLQUE { get; set; }
        [Required]
        [Display(Name = "Capacidad remolque")]
        public int CAPACIDAD_REMOLQUE { get; set; }
    
        public virtual ICollection<MOVIMIENTOS> MOVIMIENTOS { get; set; }
    }
}
