//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sivel_proyecto_bad115.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_MOVIMIENTOS
    {
        public TIPO_MOVIMIENTOS()
        {
            this.MOVIMIENTOS = new HashSet<MOVIMIENTOS>();
        }
    
        public int ID_TMOVIMIENTO { get; set; }
        public string TIPO_MOVIMIENTO { get; set; }
    
        public virtual ICollection<MOVIMIENTOS> MOVIMIENTOS { get; set; }
    }
}
