//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sivel_proyecto_bad115.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int ID_USUARIO { get; set; }
        public int ID_ROLES { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string NOMBRE_USER { get; set; }
    
        public virtual ROLES ROLES { get; set; }
    }
}
