//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sivel_proyecto_bad115.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int ID_USUARIO { get; set; }
        public int ID_ROLES { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string NOMBRE_USER { get; set; }
    
        public virtual ROLES ROLES { get; set; }
    }
}
