//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sivel_proyecto_bad115.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULOS
    {
        public VEHICULOS()
        {
            this.IMPORTACIONES = new HashSet<IMPORTACIONES>();
        }
    
        public int ID_VEHICULO { get; set; }
        public string MARCA { get; set; }
        public string MODELO { get; set; }
        public int ANO { get; set; }
    
        public virtual ICollection<IMPORTACIONES> IMPORTACIONES { get; set; }
    }
}
