//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sivel_proyecto_bad115
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_IMPORTACIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESTADO_IMPORTACIONES()
        {
            this.IMPORTACIONES = new HashSet<IMPORTACIONES>();
        }
    
        public int ID_EIMPORTACION { get; set; }
        public string ESTADO_IMPORTACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPORTACIONES> IMPORTACIONES { get; set; }
    }
}
