//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sivel_proyecto_bad115
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTOS
    {
        public int ID_MOVIMIENTO { get; set; }
        public Nullable<int> ID_TALLER { get; set; }
        public int ID_IMPORTACION { get; set; }
        public int ID_TMOVIMIENTO { get; set; }
        public Nullable<int> ID_TREMOLQUE { get; set; }
        public System.DateTime FECHA { get; set; }
    
        public virtual IMPORTACIONES IMPORTACIONES { get; set; }
        public virtual TIPO_MOVIMIENTOS TIPO_MOVIMIENTOS { get; set; }
        public virtual TIPO_REMOLQUES TIPO_REMOLQUES { get; set; }
        public virtual TALLERES TALLERES { get; set; }
    }
}
